name: Build Develop

on:
  push:
    branches: ["develop"]

jobs:
  build:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Ruby & Bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true

      - name: Deploy to Firebase App Distribution
        run: |
          echo $SA_JSON_KEY | base64 -d -i > key_firebase.json
          bundle exec fastlane firebase_distribution
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_APP_DISTRIBUTION_SECRET: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SECRET }}
          CI_PR_TITLE: ${{ github.event.pull_request.title }}
          CI_COMMIT_BEFORE_SHA: ${{ github.event.before }}
          CI_ENVIRONMENT_NAME: ${{ github.workflow }}
          CI_PIPELINE_ID: ${{ github.run_number }}
